import { Plugin, ResolvedConfig } from "vite";
import { writeFileSync, readdirSync, statSync } from "fs";
import { resolve } from "path";
import { execFileSync } from "child_process";

type ChangeFreq = "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";

interface RouteConfig {
  path: string;
  changefreq: ChangeFreq;
  priority: string;
  /** Files to check for lastmod date (relative to src/) */
  sourceFiles?: string[];
}

const routes: RouteConfig[] = [
  {
    path: "/",
    changefreq: "monthly",
    priority: "1.0",
    sourceFiles: ["pages/AboutPage.vue"],
  },
  {
    path: "/about",
    changefreq: "monthly",
    priority: "0.8",
    sourceFiles: ["pages/AboutPage.vue", "domain/about/data.ts"],
  },
  {
    path: "/experience",
    changefreq: "monthly",
    priority: "0.8",
    sourceFiles: ["pages/ExperiencePage.vue", "domain/experience/data.ts"],
  },
  {
    path: "/tech-radar",
    changefreq: "weekly",
    priority: "0.9",
    sourceFiles: ["pages/TechRadarHomePage.vue", "pages/TechRadarViewPage.vue"],
  },
  {
    path: "/devlog",
    changefreq: "weekly",
    priority: "0.9",
    sourceFiles: ["pages/DevLogPage.vue"],
  },
];

/**
 * Get the last git commit date for a file, or fall back to file mtime
 */
function getLastModified(filePath: string): string | null {
  try {
    // Try git log first - use execFileSync with args array to avoid shell injection
    const gitDate = execFileSync("git", ["log", "-1", "--format=%cI", "--", filePath], {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();

    if (gitDate) {
      return gitDate.split("T")[0]; // Return just the date part (YYYY-MM-DD)
    }
  } catch {
    // Git command failed, try file stat
  }

  try {
    const stats = statSync(filePath);
    return stats.mtime.toISOString().split("T")[0];
  } catch {
    return null;
  }
}

/**
 * Get the most recent lastmod date from multiple source files
 */
function getRouteLastModified(sourceFiles: string[], srcPath: string): string | null {
  const dates: string[] = [];

  for (const file of sourceFiles) {
    const fullPath = resolve(srcPath, file);
    const date = getLastModified(fullPath);
    if (date) {
      dates.push(date);
    }
  }

  // Also check devlog entries for the /devlog route
  if (sourceFiles.some((f) => f.includes("DevLogPage"))) {
    const devlogPath = resolve(srcPath, "../public/devlog");
    try {
      const files = readdirSync(devlogPath).filter((f) => f.endsWith(".md"));
      for (const file of files) {
        const date = getLastModified(resolve(devlogPath, file));
        if (date) {
          dates.push(date);
        }
      }
    } catch {
      // devlog directory doesn't exist
    }
  }

  if (dates.length === 0) return null;

  // Return the most recent date
  return dates.sort().reverse()[0];
}

/**
 * Generate a sitemap URL entry
 */
function generateUrlEntry(
  siteUrl: string,
  route: RouteConfig,
  lastmod: string | null
): string {
  const lines = [
    "  <url>",
    `    <loc>${siteUrl}${route.path}</loc>`,
  ];

  if (lastmod) {
    lines.push(`    <lastmod>${lastmod}</lastmod>`);
  }

  lines.push(
    `    <changefreq>${route.changefreq}</changefreq>`,
    `    <priority>${route.priority}</priority>`,
    "  </url>"
  );

  return lines.join("\n");
}

/**
 * Plugin to generate sitemap.xml with correct hostname and lastmod dates
 */
export function sitemapPlugin(): Plugin {
  let outDir: string;
  let root: string;

  return {
    name: "vite-plugin-seo-sitemap",
    configResolved(config: ResolvedConfig) {
      outDir = config.build.outDir;
      root = config.root;
    },
    closeBundle() {
      const siteUrl = (process.env.VITE_SITE_URL || "https://dev.caiokf.com").replace(/\/$/, "");
      const srcPath = resolve(root, "src");

      const urlEntries = routes.map((route) => {
        const lastmod = route.sourceFiles
          ? getRouteLastModified(route.sourceFiles, srcPath)
          : null;
        return generateUrlEntry(siteUrl, route, lastmod);
      });

      const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by vite-plugins/seo-sitemap.ts at build time -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries.join("\n")}
</urlset>`;

      writeFileSync(resolve(outDir, "sitemap.xml"), sitemap);
      console.log("✓ Generated sitemap.xml with lastmod dates");
    },
  };
}
