import { Plugin } from "vite";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

interface RouteConfig {
  path: string;
  changefreq: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  priority: string;
}

const routes: RouteConfig[] = [
  { path: "/", changefreq: "monthly", priority: "1.0" },
  { path: "/about", changefreq: "monthly", priority: "0.8" },
  { path: "/experience", changefreq: "monthly", priority: "0.8" },
  { path: "/tech-radar", changefreq: "weekly", priority: "0.9" },
  { path: "/devlog", changefreq: "weekly", priority: "0.9" },
];

/**
 * Plugin to generate sitemap.xml with correct hostname
 */
export function sitemapPlugin(): Plugin {
  return {
    name: "vite-plugin-seo-sitemap",
    closeBundle() {
      const siteUrl = (process.env.VITE_SITE_URL || "https://dev.caiokf.com").replace(/\/$/, "");
      const distPath = resolve(__dirname, "../../../dist");

      const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by vite-plugins/seo-sitemap.ts -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${routes
  .map(
    (r) => `  <url>
    <loc>${siteUrl}${r.path}</loc>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`
  )
  .join("\n")}
</urlset>`;

      writeFileSync(resolve(distPath, "sitemap.xml"), sitemap);
    },
  };
}
